# Generated by Django 2.2.6 on 2019-11-02 16:46

import django.core.validators
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('startapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details_client',
            name='Adress',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='details_client',
            name='Email',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='details_client',
            name='First_Name',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='details_client',
            name='Last_Name',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='details_client',
            name='Phone',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='oders',
            name='Order_No_Client',
            field=jsonfield.fields.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='oders',
            name='Price',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
