# Generated by Django 2.2.6 on 2019-11-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startapp', '0002_auto_20191102_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='details_client',
            name='Completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
